# Generated by Django 3.2.6 on 2021-08-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
