# Generated by Django 3.2.6 on 2021-08-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210804_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item'),
        ),
    ]
