# Generated by Django 3.2.6 on 2021-08-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_inventory_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='game.Item'),
        ),
    ]
