# Generated by Django 3.2.6 on 2021-08-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
