# Generated by Django 3.2.6 on 2021-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210804_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
