# Generated by Django 3.2.6 on 2021-08-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_item_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='items',
        ),
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item')),
            ],
        ),
    ]
