# Generated by Django 3.2.6 on 2021-08-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210805_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('base_force', models.BigIntegerField()),
                ('base_resistence', models.BigIntegerField()),
                ('base_agility', models.BigIntegerField()),
                ('base_level', models.BigIntegerField()),
                ('type_class', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='gold',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.BigIntegerField()),
                ('resistence', models.BigIntegerField()),
                ('agility', models.BigIntegerField()),
                ('level', models.BigIntegerField()),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.char')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.inventory')),
                ('skill_1', models.ManyToManyField(to='game.Item')),
            ],
        ),
    ]
